#keyboard
input {
    kb_layout = fr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 à 1.0, 0 = par défaut pour la souris
}

#monior
# Syntaxe : monitor = name, resolution@frequence, position, scale
monitor=,preferred,auto,1

#keybind

$mainMod = SUPER

# Base keybinds
bind = $mainMod, T, exec, kitty
bind = $mainMod, Q, killactive
bind = $mainMod, M, exit
bind = $mainMod, E, exec, dolphin
bind = $mainMod, L, togglefloating
bind = $mainMod, A, exec, $HOME/.config/rofi/launchers/type-6/launcher.sh
bind = $mainMod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = $mainMod, B, exec, firefox
bind = $mainMod, exclam, exec, ~/.config/hypr/scripts/shortcuts.sh

# Moving windows with the arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# auto start
exec-once = waybar
exec-once = hyprpaper
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# --- NAVIGUER ENTRE LES BUREAUX ---
# swithing between desktop
bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft, workspace, 5
bind = $mainMod, minus, workspace, 6
bind = $mainMod, egrave, workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla, workspace, 9
bind = $mainMod, agrave, workspace, 10

# moving the current windows to an desktop
bind = $mainMod SHIFT, ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, eacute, movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl, movetoworkspace, 3
bind = $mainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, parenleft, movetoworkspace, 5
bind = $mainMod SHIFT, minus, movetoworkspace, 6
bind = $mainMod SHIFT, egrave, movetoworkspace, 7
bind = $mainMod SHIFT, underscore, movetoworkspace, 8
bind = $mainMod SHIFT, ccedilla, movetoworkspace, 9
bind = $mainMod SHIFT, agrave, movetoworkspace, 10
# swithing desk with mouse
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1


# --- CAPTURES D'ÉCRAN ---

# 1. Sélectionner une zone et copier l'image dans le presse-papier ($mainMod + SHIFT + S)
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" /tmp/tmp_shot.png && wl-copy --type image/png < /tmp/tmp_shot.png && rm /tmp/tmp_shot.png

# 2. Capturer tout l'écran dans le presse-papier (Touche Print)
bind = , Print, exec, grim - | wl-copy --type image/png

# 3. Sélectionner une zone ET enregistrer un fichier image dans ~/Images
bind = $mainMod, Print, exec, grim -g "$(slurp)" ~/Images/screenshot_$(date +'%Y%m%d_%H%M%S').png

ecosystem:no_update_news = true

#animation speed
animations {
    enabled = yes

    # Définition des courbes de bézier (smoothness)
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    # Syntaxe : animation = NOM, ACTIVÉ, DURÉE (en 100ms), COURBE [, STYLE]
    
    # Fenêtres qui s'ouvrent / se ferment (ex: 2 = 0.2s au lieu de 7 par défaut)
    animation = windows, 1, 2, myBezier
    animation = windowsOut, 1, 2, default, popin 80%
    
    # Bordures et fondus (fade)
    animation = border, 1, 3, default
    animation = fade, 1, 2, default
    
    # Changement d'espace de travail / workspaces (ex: 3 = 0.3s)
    animation = workspaces, 1, 3, default
}
